import { useEffect, useState } from 'react'
import { apiRequest } from '../services/apiClient'
import { appConfig } from '../core/config'
import type { UploadedDocument } from '../types/clinical'
import './records.css'
export function DocumentTimeline({ caseId, language }: { caseId:string; language:string }) {
  const hi=language!=='English',t=(h:string,e:string)=>hi?h:e
  const [documents,setDocuments]=useState<UploadedDocument[]>([]),[error,setError]=useState(''),[edit,setEdit]=useState<UploadedDocument|null>(null),[busy,setBusy]=useState(false)
  useEffect(()=>{let alive=true;apiRequest<UploadedDocument[]>(`/api/v1/cases/${caseId}/timeline`).then(data=>{if(alive)setDocuments(data)}).catch(()=>{if(alive)setError(t('रिपोर्ट लोड नहीं हुई।','Could not load reports.'))});return()=>{alive=false}},[caseId,hi])
  const save=async()=>{if(!edit)return;setBusy(true);setError('');try{await apiRequest(`/api/v1/documents/${edit.id}`,{method:'PATCH',body:JSON.stringify({documentDate:edit.documentDate||null,extractedText:edit.extractedText,reviewed:true})});setDocuments(await apiRequest<UploadedDocument[]>(`/api/v1/cases/${caseId}/timeline`));setEdit(null)}catch(cause){setError(cause instanceof Error?cause.message:'Could not save.')}finally{setBusy(false)}}
  return <section className="document-timeline"><h2>{t('रिपोर्ट की समयरेखा','Report timeline')}</h2><p>{t('पुष्टि की गई रिपोर्ट तारीख के क्रम में; अज्ञात तारीख वाले रिकॉर्ड अंत में हैं।','Ordered by confirmed report date, oldest first. Undated records are shown last.')}</p>{error&&<p role="alert">{error}</p>}{!documents.length&&<p>{t('इस मुलाकात में कोई स्कैन नहीं जोड़ा गया।','No scans attached to this visit.')}</p>}{documents.map(doc=><article key={doc.id} className="timeline-record"><h3>{doc.documentDate||t('तारीख अज्ञात','Undated')} · {doc.fileType.replace(/_/g,' ')}</h3><details><summary>{t('स्कैन और पढ़ा गया टेक्स्ट देखें','View scan and extracted text')}</summary><a href={`${appConfig.apiBaseUrl}/api/v1/documents/${doc.id}/image?original=true`} target="_blank" rel="noreferrer">{t('मूल कैमरा फोटो देखें','Open original camera image')}</a><img className="record-preview" loading="lazy" src={`${appConfig.apiBaseUrl}/api/v1/documents/${doc.id}/image`} alt={t('रिपोर्ट का स्कैन','Scanned report')}/><pre className="ocr-text">{doc.extractedText||t('टेक्स्ट नहीं पढ़ा गया — फोटो जांचें।','No text recognized — review the image.')}</pre>{doc.abbreviations.map(a=><p key={a.abbreviation}><strong>{a.abbreviation}</strong>: {a.candidates.join(' / ')} ({t('पुष्टि बाकी','unconfirmed')})</p>)}<button className="secondary-button" onClick={()=>setEdit(doc)}>{t('टेक्स्ट / तारीख सुधारें','Correct text / date')}</button></details>{edit?.id===doc.id&&<div><label>{t('रिपोर्ट की तारीख','Report date')}<input type="date" value={edit.documentDate||''} onChange={e=>setEdit({...edit,documentDate:e.target.value||null})}/></label><label>{t('टेक्स्ट','Text')}<textarea rows={8} value={edit.extractedText} onChange={e=>setEdit({...edit,extractedText:e.target.value})}/></label><div className="record-actions"><button className="primary-button" disabled={busy} onClick={()=>void save()}>{t('सुधार सेव करें','Save corrections')}</button><button className="secondary-button" disabled={busy} onClick={()=>setEdit(null)}>{t('रद्द करें','Cancel')}</button></div></div>}</article>)}</section>
}
