import { useEffect, useState } from 'react'
import { CalendarDays, Save } from 'lucide-react'
import { apiRequest } from '../services/apiClient'
import type { CaseDraft, Followup } from '../types/clinical'
import './records.css'
export function FollowupPanel({ visit, language, onChange }: { visit: CaseDraft; language: string; onChange: () => void }) {
  const hi=language!=='English',t=(h:string,e:string)=>hi?h:e
  const [jobs,setJobs]=useState<Followup[]>([]),[date,setDate]=useState(''),[time,setTime]=useState('10:00'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(false)
  const [mobile,setMobile]=useState(visit.patient?.mobile??''),[consent,setConsent]=useState(visit.patient?.smsConsent??false),[message,setMessage]=useState('')
  const url=`/api/v1/cases/${encodeURIComponent(visit.id)}/followup`
  useEffect(()=>{let alive=true;const load=async()=>{try{const [rows,status]=await Promise.all([apiRequest<Followup[]>(url),apiRequest<{configured:boolean}>('/api/v1/followups/status')]);if(alive){setJobs(rows);setConfigured(status.configured)}}catch{if(alive)setError(t('फॉलो-अप लोड नहीं हुआ।','Could not load follow-up.'))}};void load();const timer=setInterval(load,5000);return()=>{alive=false;clearInterval(timer)}},[url,hi])
  const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setMessage('');try{await fn();setJobs(await apiRequest<Followup[]>(url));onChange();setMessage(t('सेव हो गया।','Saved.'))}catch(cause){setError(cause instanceof Error?cause.message:'Could not save follow-up.')}finally{setBusy(false)}}
  const statuses:Record<string,string>={scheduled:t('तारीख तय — SMS बाकी','Scheduled — SMS pending'),blocked:t('तारीख तय — SMS सेवा सेटअप बाकी','Scheduled — SMS setup pending'),retry:t('SMS फिर भेजने की कोशिश बाकी','SMS retry pending'),sending:t('SMS भेज रहे हैं','Sending SMS'),accepted:t('SMS सेवा ने स्वीकार किया','Accepted by SMS provider'),sent:t('SMS भेजा गया','SMS sent'),delivered:t('SMS पहुंच गया','SMS delivered'),failed:t('SMS नहीं भेजा गया','SMS failed'),undelivered:t('SMS नहीं पहुंचा','SMS undelivered'),delivery_unknown:t('SMS की स्थिति अस्पष्ट — स्टाफ जांचें','SMS status unknown — staff review needed'),cancelled:t('रद्द','Cancelled'),missed:t('याद दिलाने का दिन निकल गया — स्टाफ संपर्क करें','Reminder day missed — staff contact needed')}
  return <section className="followup-panel"><h2><CalendarDays/>{t('फॉलो-अप तय करें','Schedule follow-up')}</h2>{visit.status!=='approved'?<p>{t('फॉलो-अप तय करने से पहले केस स्वीकार करें।','Accept this case before scheduling a follow-up.')}</p>:<>
    <p>{t('पंजीकृत मोबाइल','Registered mobile')}: <strong>{visit.patient?.mobile||t('नंबर नहीं है','Not registered')}</strong></p>
    {(!visit.patient?.mobile||!visit.patient?.smsConsent)&&<fieldset><legend>{t('मरीज़ का संपर्क और अनुमति','Patient contact and permission')}</legend><label>{t('मोबाइल नंबर','Mobile number')}<input type="tel" value={mobile} onChange={e=>setMobile(e.target.value)} placeholder="+91"/></label><label className="record-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t('मरीज़ इस नंबर पर फॉलो-अप SMS के लिए सहमत हैं।','The patient agrees to follow-up SMS on this number.')}</label><button className="secondary-button" disabled={busy||!mobile} onClick={()=>void action(()=>apiRequest(`/api/v1/patients/${visit.patientId}/contact`,{method:'PATCH',body:JSON.stringify({mobile,smsConsent:consent})}))}>{t('संपर्क सेव करें','Save contact')}</button></fieldset>}
    <div className="record-fields"><label>{t('फॉलो-अप की तारीख','Follow-up date')}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{t('समय (भारत)','Time (India)')}<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><p>{t('उसी दिन सुबह 9 बजे SMS जाएगा; पहले की मुलाकात हो तो उसके समय पर।','The reminder is due at 9 AM on that day, or at the visit time for earlier appointments.')}</p>{!configured&&<p role="status">{t('SMS सेवा सेटअप बाकी है। तारीख सेव होगी, लेकिन सेवा जुड़ने तक संदेश नहीं जाएगा।','SMS provider setup is pending. The date will be saved, but messages cannot send until it is connected.')}</p>}
    <button className="primary-button" disabled={busy||!date||!time||!visit.patient?.mobile||!visit.patient?.smsConsent} onClick={()=>void action(()=>apiRequest(url,{method:'POST',body:JSON.stringify({date,time,version:visit.version})}))}><Save/>{t('फॉलो-अप सेव करें','Save follow-up')}</button>
  </>}{error&&<p role="alert" className="inline-error">{error}</p>}{message&&<p role="status">{message}</p>}
    <ul className="followup-list">{jobs.map(job=><li key={job.id}><strong>{job.date} · {job.time} IST</strong><p>{statuses[job.status]??job.status}</p>{['scheduled','retry','blocked'].includes(job.status)&&<button className="secondary-button" disabled={busy} onClick={()=>void action(()=>apiRequest(`${url}/${job.id}`,{method:'DELETE'}))}>{t('फॉलो-अप रद्द करें','Cancel follow-up')}</button>}</li>)}</ul>
  </section>
}
