import { useEffect, useState } from 'react'
import { CalendarDays, Check, Save, X } from 'lucide-react'
import { apiRequest } from '../services/apiClient'
import type { CaseDraft, Followup } from '../types/clinical'
import './records.css'
export function FollowupPanel({ visit, language, onChange }: { visit: CaseDraft; language: string; onChange: () => void }) {
  const hi=language!=='English',t=(h:string,e:string)=>hi?h:e
  const [jobs,setJobs]=useState<Followup[]>([]),[needed,setNeeded]=useState<boolean|null>(visit.followupDecision?.needed ?? null),[date,setDate]=useState(visit.followupDecision?.date??''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const url=`/api/v1/cases/${encodeURIComponent(visit.id)}/followup`
  useEffect(()=>{let alive=true;const load=async()=>{try{const rows=await apiRequest<Followup[]>(url);if(alive)setJobs(rows)}catch{if(alive)setError(t('फॉलो-अप लोड नहीं हुआ।','Could not load follow-up.'))}};void load();const timer=setInterval(load,5000);return()=>{alive=false;clearInterval(timer)}},[url,hi])
  const save=async()=>{setBusy(true);setError('');setMessage('');try{await apiRequest(url,{method:'POST',body:JSON.stringify({needed,date:needed?date:null,version:visit.version})});setJobs(await apiRequest<Followup[]>(url));onChange();setMessage(needed?t('फॉलो-अप की तारीख सेव हो गई।','Follow-up date saved.'):t('फॉलो-अप की ज़रूरत नहीं — सेव हो गया।','No follow-up needed — saved.'))}catch(cause){setError(cause instanceof Error?cause.message:'Could not save follow-up.')}finally{setBusy(false)}}
  const statuses:Record<string,string>={scheduled:t('SMS तय तारीख पर जाएगा','Reminder scheduled'),blocked:t('तारीख सेव — SMS सेवा सेटअप बाकी','Date saved — SMS setup pending'),awaiting_contact:t('तारीख सेव — पंजीकरण पर मोबाइल/अनुमति पूरी करें','Date saved — registration team needs mobile/SMS consent'),retry:t('SMS फिर भेजने की कोशिश बाकी','SMS retry pending'),sending:t('SMS भेज रहे हैं','Sending SMS'),accepted:t('SMS सेवा ने स्वीकार किया','Accepted by SMS provider'),sent:t('SMS भेजा गया','SMS sent'),delivered:t('SMS पहुंच गया','SMS delivered'),failed:t('SMS नहीं भेजा गया','SMS failed'),undelivered:t('SMS नहीं पहुंचा','SMS undelivered'),delivery_unknown:t('SMS स्थिति अस्पष्ट — स्टाफ जांचें','SMS status unknown — staff review'),cancelled:t('रद्द','Cancelled'),missed:t('याद दिलाने का दिन निकल गया','Reminder day missed')}
  return <section className="followup-panel"><h2><CalendarDays/>{t('क्या फॉलो-अप चाहिए?','Does the patient need a follow-up?')}</h2>{visit.status!=='approved'?<p>{t('पहले केस स्वीकार करें।','Accept this case first.')}</p>:<><div className="record-actions" role="group" aria-label={t('फॉलो-अप की ज़रूरत','Follow-up needed')}><button className={needed===true?'primary-button':'secondary-button'} aria-pressed={needed===true} disabled={busy} onClick={()=>{setNeeded(true);setMessage('')}}><Check/>{t('हाँ','Yes')}</button><button className={needed===false?'primary-button':'secondary-button'} aria-pressed={needed===false} disabled={busy} onClick={()=>{setNeeded(false);setMessage('')}}><X/>{t('नहीं','No')}</button></div>{needed===true&&<label>{t('फॉलो-अप की तारीख','Follow-up date')}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{needed!==null&&<button className="primary-button" disabled={busy||(needed&&!date)} onClick={()=>void save()}><Save/>{t('निर्णय सेव करें','Save follow-up decision')}</button>}</>}{error&&<p role="alert" className="inline-error">{error}</p>}{message&&<p role="status">{message}</p>}
    <ul className="followup-list">{jobs.filter(job=>job.status!=='cancelled').map(job=><li key={job.id}><strong>{job.date}</strong><p>{statuses[job.status]??job.status}</p></li>)}</ul>
  </section>
}
