import { useState } from 'react'
import { AlertTriangle, Check } from 'lucide-react'
import type { OcrElement } from '../types/clinical'
export function OcrConfidence({ elements = [], threshold = 85, language, onConfirm }: { elements?: OcrElement[]; threshold?: number; language: string; onConfirm?: (entry: OcrElement, value: string) => Promise<void> }) {
  const hi=language!=='English',t=(h:string,e:string)=>hi?h:e
  const [selected,setSelected]=useState<string|null>(null),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  return <section className="ocr-confidence"><h3>{t('पढ़ी गई जानकारी और भरोसे का स्कोर','Extracted entries & confidence')}</h3><p>{t(`OCR स्कोर चिकित्सा की पुष्टि नहीं है। ${threshold}% से कम या अस्पष्ट जानकारी डॉक्टर जांचेंगे।`,`OCR confidence is not medical certainty. Entries below ${threshold}% or with ambiguity need doctor assurance.`)}</p>{!elements.length&&<p>{t('स्कोर उपलब्ध नहीं — मूल स्कैन डॉक्टर को दिखाएं।','No confidence data — show the original scan to the doctor.')}</p>}<div className="ocr-elements">{elements.map(entry=>{
    const pending=entry.requiresAssurance&&!entry.assurance
    return <div key={entry.id} className={`ocr-entry ${pending?'needs-assurance':''}`} data-confidence={entry.confidence??'unknown'}><span className="ocr-entry-value">{entry.value}</span><span className="confidence-score" title={entry.confidenceBasis==='line'?t('पंक्ति के OCR स्कोर से','Inherited from line OCR score'):t('OCR इंजन का स्कोर','OCR engine score')}>{entry.confidence===null?'—':`${entry.confidence}%`}</span>{pending&&<span className="assurance-label"><AlertTriangle size={16}/>{t('डॉक्टर की पुष्टि चाहिए','Needs doctor assurance')}</span>}{entry.assurance&&<span className="assured-label"><Check size={16}/>{t('डॉक्टर ने पुष्टि की','Doctor confirmed')}</span>}{pending&&entry.candidates&&<small>{entry.candidates.join(' / ')}</small>}{onConfirm&&pending&&<button className="text-button" onClick={()=>{setSelected(entry.id);setValue(entry.value);setError('')}}>{t('जांचें / सुधारें','Review / correct')}</button>}{selected===entry.id&&onConfirm&&<div className="assurance-editor"><label>{t('स्कैन से मिलाकर सही मान लिखें','Check the scan and enter the correct value')}<input value={value} onChange={e=>setValue(e.target.value)}/></label><button className="secondary-button" disabled={busy||!value.trim()} onClick={async()=>{setBusy(true);try{await onConfirm(entry,value);setSelected(null)}catch(cause){setError(cause instanceof Error?cause.message:'Could not confirm.')}finally{setBusy(false)}}}><Check/>{t('डॉक्टर पुष्टि करें','Confirm as doctor')}</button>{error&&<p role="alert">{error}</p>}</div>}</div>
  })}</div></section>
}
